apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  # The value is base64 encoded - replace with your actual password
  # Use: echo -n "yourpassword" | base64
  POSTGRES_PASSWORD: cG9zdGdyZXM=
